### ISSUE TITLE
Correção Material Bootcamp - Do zero à Implantação

### ISSUE THREAD

**Issue by sascarpin** [cassiobotaro/cassiobotaro#1]
Em "INICIANDO UM PROJETO", após clonar o repositório, é bom informar que as linhas seguintes vão ser executadas no prompt de comando. Pode colocar também no material o Win+R pra abrir o executar e um print escrevendo "cmd".

![issue 1](https://user-images.githubusercontent.com/105754170/168927044-211dc99d-8378-41e7-bc10-31a6fd4b371f.PNG)

**Comment by cassiobotaro** [comment]
Acho que esta _issue_ está duplicada no repositório do curso, por isso vou fechar aqui.
